name: Run main.py Every 3 Hours

on:
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Change to your Python version if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Ensure dependencies are listed in requirements.txt

      - name: Run main.py
        run: python main.py
